//
//  stringConstant.swift
//  Shophop
//
//  Created by  on 14/10/19.
//  Copyright © 2019 . All rights reserved.
//

import Foundation

let SHOPHOP_Fashion = "Fashion"
let SHOPHOP_Kids = "Kids"
let SHOPHOP_Clothing = "Clothing"
let SHOPHOP_Men = "Men"
let SHOPHOP_Women = "Women"
let SHOPHOP_Optics = "Optics"
let SHOPHOP_Bags = "Bags"
let SHOPHOP_Watches = "Watches"
let SHOPHOP_Footwear = "Footwear"
let SHOPHOP_Sport = "Sport"
let SHOPHOP_Decor = "Decor"


// BANKING STRING:-

let Banking_App_Name = "Cy Captial Bank"
let Banking_App_Sub_Title = "Mobile Banking Apps"
let Banking_lbl_Walk1 = "Online Payment"
let Banking_lbl_Walk2 = "Qucikly Transfer"
let Banking_lbl_Walk3 = "Saving Online"
let Banking_lbl_SubTitle = "Each payment process is so simple and hassle- free and i do not need to be worried about being scammed Each payment process is so simple and hassle-free"
let Banking_lbl_Get_Started = "Get Started"
let Banking_lbl_SignIn = "Sign In"
let Banking_lbl_Phone = "Phone"
let Banking_lbl_Password = "Password"
let Banking_lbl_login_with_FaceID = "Or Login With Face ID"
let Banking_lbl_Forgot = "Forgot?"
let Banking_lbl_Next = "Next"
let Banking_lbl_Resend = "Resend?"
let Banking_lbl_Forgot_Password = "Forgot \nPassword"
let Banking_lbl_Change_Pwd = "Change \nPassword"
let Banking_lbl_Confirm = "Confirm"
let Banking_lbl_Menu = "Menu"
let Banking_lbl_Settings = "Settings"
let Banking_lbl_Change_Password = "Change Password"
let Banking_lbl_Share_Information_Account = "Share Information Account"
let Banking_lbl_News = "News"
let Banking_lbl_Rate_Information = "Rate Information"
let Banking_lbl_Location = "Location"
let Banking_lbl_Terms_Condition = "Terms & Conditions"
let Banking_lbl_Question_Answers = "Questions & Answers"
let Banking_lbl_Contact = "Contact"
let Banking_lbl_Logout = "Logout"
let Banking_lbl_Share_Information = "Share \nInformation"
let Banking_lbl_Rate_Info = "Rate \nInformation"
let Banking_lbl_Terms_Condtion = "Terms & Condition"
let Banking_lbl_Saving_Online = "Saving Online"
let Banking_lbl_Add_New_Saving = "Add New Saving"
let Banking_lbl_Save_Successful = "Save \nSuceessful"
let Banking_lbl_View_Saving = "View Saving"
let Banking_lbl_Transaction_History = "Transaction History"
let Banking_lbl_Transaction_Successful = "Transaction \nSuccessful"
let Banking_lbl_Transfer = "Transfer"
let Banking_lbl_Confirm_Transfer = "Confirm Transfer"
let Banking_lbl_Get_Otp = "Get OTP"
let Banking_lbl_Payment = "Payment"
let Banking_lbl_Pay_Invoice = "Pay Invoice"
let Banking_lbl_Invoice = "Payment Inovice #7783"
let Banking_lbl_Pay = "Pay"
let Banking_lbl_Payment_History = "Payment \nHistory"
let Banking_lbl_Branch_Location = "Branch \nLocation"
let Banking_lbl_Beneficiary_List = "Beneficiary List"


// Fitness App

let Fitness_lbl_walkTitle1 = "Make Yourself Better"
let Fitness_lbl_walkTitle2 = "Personalised Trainning"
let Fitness_lbl_walkTitle3 = "Make yourself Stronger"
let Fitness_lbl_walkTitle4 = "Make yourself Stronger"
let Fitness_lbl_Get_Fit_Trainning = "Get fit with our \nprofessional \ntranning courses"
let Fitness_lbl_Create_Account = "Create Account"
let Fitness_lbl_walksubTitle = "Personalizes workouts and plans for any fitness \nand goal level"
let Fitness_lbl_Skip = "Skip"
let Fitness_lbl_View_go = "View and Go"
let Fitness_lbl_Smart_Skilled = "Smart & Skilled"
let Fitness_lbl_Personalized_Trainning = "Personalised Trainning"
let Fitness_lbl_Better_Improved = "Better & Improved"
let Fitness_lbl_Login = "Login"
let Finess_lbl_Continue_fb = "Continue with Facebook"
let Fitness_lbl_Create_Account_with_Email = "Create Account with Email"
let Fitness_lbl_Welcome_Back = "Welcome back \nMiranda"
let Fitness_lbl_Forgot_Password = "Forgot Password?"
let Fitness_lbl_Forgot_Pwd = "Forgot \nPassword?"
let Fitness_lbl_Send = "Send"
let Fitness_lbl_Uppar_Body = "Upper Body Workout"
let Fitness_lbl_Follow = "Follow"
let Fitness_lbl_User_Name = "Carly \nJackson"
let Fitness_lbl_Split_Squat = "Split \nSquat"
let Fitness_lbl_Notification = "Notifications"
let Fitness_lbl_Save_Training = "Save Training"
let Fitness_lbl_Next = "Next"
let Fitness_lbl_Cancel = "Cancel"
