//
//  TConfig.swift
//

//  Copyright © 2018 "". All rights reserved.
//

import Foundation
import UIKit

// Common

let IPAD = UI_USER_INTERFACE_IDIOM() == .pad
let IS_IPHONE_4_OR_LESS  = UIDevice.current.userInterfaceIdiom == .phone
let IS_IPHONE_5          = UIDevice.current.userInterfaceIdiom == .phone

let SCREEN_SIZE = UIScreen.main.bounds.size

//Live
let ADMOB_ID = "ca-app-pub-4937593957421986~3459489438"
let BANNER_ID = "ca-app-pub-3940256099942544/6300978111"
let INTERSTITIAL_ID = "ca-app-pub-3940256099942544/1033173712"

// Cricket

let CRICKET_PRIMARY_COLOR = "#ffe000"
let CRICKET_HEADER_BG_COLOR = "#2978E6"
let CRICKET_DID_SELECT_COLOR = "#F92C5B"
let CRICKET_COLOR1 = "#232883"
let CRICKET_COLOR2 = "#232883"
let CRICKET_TITLE_COLOR1 = "#30DD7F"
let CRICKET_TITLE_COLOR2 = "#30C2C1"
let CRICKET_TITLE_COLOR3 = "#4550FC"
let CRICKET_TITLE_COLOR4 = "#308EFA"
let CRICKET_PRIMARY_COLOR_DARK = "#799f0c"
let CRICKET_PRIMARY_COLOR_LIGHT = "#232883"
let CRICKET_CELL_COLOR1 = "#27337e"
let CRICKET_CELL_COLOR2 = "#EE2F56"
let CRICKET_SQUAD_BG_COLOR = "#12154E"

let CRICKET_PRIMARY_FONT = "GoogleSans-Regular"
let CRICKET_PRIMARY_FONT_BOLD = "GoogleSans-Bold"

let CRICKET_SIZE_XXLARGE:Float = 30
let CRICKET_SIZE_XLARGE:Float = 24
let CRICKET_SIZE_LARGE:Float = 20
let CRICKET_SIZE_NORMAL:Float = 18
let CRICKET_SIZE_MEDIUM:Float = 16
let CRICKET_SIZE_MSMALL:Float = 14
let CRICKET_SIZE_SMALL:Float = 12
let CRICKET_SIZE_TINY:Float = 10

let MatchID = "match_id"

let WC_SERIES_ID = "2697"

//QIBus

let QIBUS_PRIMARY_COLOR = "#eb4b51"

let QIBUS_PRIMARY_TEXT_COLOR = "#464545"
let QIBUS_SECONDARY_TEXT_COLOR = "#747474"
let QIBUS_BTN_TEXT_COLOR = "#ffffff"
let QIBUS_GREEN = "#239811"
let QIBUS_DARK_GRAY = "#949494"
let QIBUS_LIGHT_GRAY = "#c9c9c9"

let QIBUS_PRIMARY_FONT = "Roboto-Regular"
let QIBUS_PRIMARY_FONT_SEMIBOLD = "Roboto-Bold"
let QIBUS_PRIMARY_FONT_BOLD = "Roboto-Black"

let QIBUS_SIZE_XXXLARGE:Float = 35
let QIBUS_SIZE_XXLARGE:Float = 30
let QIBUS_SIZE_XLARGE:Float = 24
let QIBUS_SIZE_LARGE:Float = 20
let QIBUS_SIZE_NORMAL:Float = 18
let QIBUS_SIZE_MEDIUM:Float = 16
let QIBUS_SIZE_MSMALL:Float = 14
let QIBUS_SIZE_SMALL:Float = 12
let QIBUS_SIZE_TINY:Float = 10

//DashBoard 7
let DASHBOARD7_PRIMARYCOLOR = "#4EC77F"

//Shophop

let SHOPHOP_PRIMARY_FONT = "Montserrat-Bold"
let SHOPHOP_PRIMARY_FONT_BOLD = "Montserrat-Regular"

let SHOPHOP_SCREEN_SIZE = UIScreen.main.bounds.size

let SHOPHOP_SIZE_XXLARGE:Float = 30
let SHOPHOP_SIZE_XLARGE:Float = 24
let SHOPHOP_SIZE_LARGE:Float = 20
let SHOPHOP_SIZE_NORMAL:Float = 18
let SHOPHOP_SIZE_MEDIUM:Float = 16
let SHOPHOP_SIZE_MSMALL:Float = 14
let SHOPHOP_SIZE_SMALL:Float = 12
let SHOPHOP_SIZE_TINY:Float = 10

//Common
let COMMON_SHADOW_COLOR = "#636363"

//Education
let EDUCATION_PRIMARY_COLOR1 = "5362FB"
let EDUCATION_PRIMARY_COLOR2 = "3D50FC"
let EDUCATION_LIGHT_COLOR = "ACB5FD"

//Learner
let LEARNER_PRIMARY_COLOR = "345FFB"
let LEARNER_SHADOW_COLOR = "666666"

//Food App
let FOOD_PRIMARYCOLOR = "#3B8BEA"
let FOOD_TEXTCOLORPRIMARY = "#333333"
let FOOD_TEXTCOLORSECONDARY = "#949292"
let FOOD_BACKGORUNDCOLOR = "#F8F8F8"
let FOOD_VEG_COLOR = "#4EC77F"
let FOOD_NONVEG_COLOR = "#FF2600"
let FOOD_ORDERNOW_GRANDENTCOLOR1 = "#02BBC6"
let FOOD_ORDERNOW_GRANDENTCOLOR2 = "#84DB74"
let FOOD_BOOKTABLE_GRANDENTCOLOR1 = "#398CE8"
let FOOD_BOOKTABLE_GRANDENTCOLOR2 = "#3F77DE"
let FOOD_FOODORDER_GRANDENTCOLOR1 = "#FD825D"
let FOOD_FOODORDER_GRANDENTCOLOR2 = "#FE5052"

// App DashBoard
let DASHBOARD_CELL_BOARDCOLR = "#F8F8F8"
let DASHBOARD_TEXT_COLOR = "#515BBE"
let DASHBOARD_BUTTON_BACKGROUND_COLOR = "#F9FAFF"


//Theme2
let THEME2_PRIMARYCOLOR = "#7e05fa"
let THEME2_SECONDARYCOLOR = "#5959fc"

//Theme3
let THEME3_PRIMARYCOLOR = "#fc4a1a"
let THEME3_SECONDARYCOLOR = "#f7b733"

let BASEURL = ""

//Theme4
let THEME4_PRIMARYCOLOR = "#022C60"
let THEME4_SECONDARYCOLOR = "#f7b733"

//Theme5
let THEME5_PRIMARYCOLOR = "#5436DC"

//Theme6
let THEME6_BTN_TINT_COLOR = "#00815D"

//Theme 7
let THEME7_PRIMARY_COLOR1 = "#5362FB"
let THEME7_PRIMARY_COLOR2 = "#3D50FC"
let THEME7_LIGHT_COLOR = "#ACB5FD"

//Theme 8
let THEME8_PRIMARY_COLOR = "345FFB"

//Theme 9
let THEME9_PRIMARYCOLOR = "#313384"

//Theme 10
let THEME10_PRIMARYCOLOR = "#7e05fa"
let THEME10_SECONDARYCOLOR = "#5959fc"

//Theme11
let THEME11_PRIMARYCOLOR = "#2B5266"
let THEME11_COLOR1_GRADIENT = "#F2F5F9"
let THEME11_COLOR2_GRADIENT = "#B4C5D1"


//Social App
let SOCIAL_PRIMARYCOLOR = "#494FFB"
let SOCIAL_COLORPRIMARYDARK = "#494FFB"
let SOCIAL_COLORACCENT = "#3987E5"
let SOCIAL_BLUE = "#2A2D50"
let SOCIAL_LIGHTBLUE = "#A4999DC9"
let SOCIAL_TRANSPARENT  = "#00999DC9"
let SOCIAL_TEXTCOLORPRIMARY = "#333333"
let SOCIAL_TEXTCOLORSECONDARY = "#9D9D9D"
let SOCIAL_YELLOW = "#FFCC00"
let SOCIAL_ORANGE = "#FF7227"

//Theme 12
let THEME12_PRIMARYCOLOR = "#0A9DA3"
let THEME12_PRIMARYLIGHTCOLOR = "#3A5BFB"
let THEME12_PRIMARYTEXTCOLOR = "#B2020005"
let THEME12_SECONDARYTEXTCOLOR = "#888888"
let THEME12_SECONDARYTEXTBLUE = "#86859B"
let THEME12_GRANDIENT_COLOR1 = "#0A9DA3"
let THEME12_GRANDIENT_COLOR2 = "#0DCEAB"

//Dashboard 8
let DASHBOARD8_PRIMARYCOLOR = "#AF9177"
let DASHBOARD8_PRIMARYCOLOR_DARK = "#B79A7F"

//DATINN APP.

let DATINN_PRIMARY_COLOR = "#eb4b51"
let DATINN_PRIMARY_TEXT_COLOR = "#464545"
let DATINN_SECONDARY_TEXT_COLOR = "#747474"
let DATINN_BTN_TEXT_COLOR = "#ffffff"
let DATINN_GREEN = "#12AD6E"
let DATINN_DARK_GRAY = "#949494"
let DATINN_LIGHT_GRAY = "#c9c9c9"
let DATINN_PRIMARYCOLOR1 = "#FF3B30"
let DATINN_PRIMARYCOLOR2 = "#745AF8"

//QIBus SofUI
// Primary color for app
let PRIMARY_COLOR = "#9292EE"

// TextColor
let PRIMARY_TEXT_COLOR = "#464545"
let SECONDARY_TEXT_COLOR = "#747474"
let BTN_TEXT_COLOR = "#ffffff"
let GREEN = "#239811"
let DARK_GRAY = "#949494"
let LIGHT_GRAY = "#c9c9c9"

let BTN_TEXT_COLOR_SOFT = "#000000"

// App Font
let PRIMARY_FONT = "Roboto-Regular"
let PRIMARY_FONT_SEMIBOLD = "Roboto-Bold"
let PRIMARY_FONT_BOLD = "Roboto-Black"

//Text Size
let SIZE_XXXLARGE:Float = 35
let SIZE_XXLARGE:Float = 30
let SIZE_XLARGE:Float = 24
let SIZE_LARGE:Float = 20
let SIZE_NORMAL:Float = 18
let SIZE_MEDIUM:Float = 16
let SIZE_MSMALL:Float = 14
let SIZE_SMALL:Float = 12
let SIZE_TINY:Float = 10


// TaxiBooking

let TAXIBOOKING_PRIMARY_COLOR = "#7A6EE9"
let TAXIBOOKING_DARKGRAY_COLOR = "#434343"
let TAXIBOOKING_PINK_COLOR = "#FF85FF"
let TAXIBOOKING_BLACK_COLOR = "#000000"

// Doctor plus

let DOCTOR_PRIMARY_COLOR = "#3CCDCD"
let DOCTOR_DASHICON_COLOR = "747474"
let DOCTOR_BLUE_COLOR = "#259EEF"
let DOCTOR_GREY_COLOR = "#F0F0F0"
let DOCTOR_BLACK_COLOR = "#000000"
let DOCTOR_RED_COLOR = "#FF3B30"
let DOCTOR_MSG_COLOR = "#0BAC8D"
let DOCTOR_CAT1_COLOR = "#FF727B"
let DOCTOR_CAT2_COLOR = "#439AF8"
let DOCTOR_CAT3_COLOR = "#72D4A1"
let DOCTOR_CAT4_COLOR = "#FF727B"
let DOCTOR_LIGHTGREY_COLOR = "#D6D6D6"

let DOCTOR_APP_BACKGROUND_COLOR = "#FAFAFA"
let DOCTOR_TEXT_PRIMARYCOLOR = "#333333"
let DOCTOR_TEXT_SECONDARYCOLOR = "#9D9D9D"
let DOCTOR_TEXT_GREEN_COLOR = "#0DAF14"
let DOCTOR_DARK_ORANGE_COLOR = "#FE7858"

// Primary color for app
let PRIMARY_COLORDARK = "#DDDDFF"//9292EE
let PRIMARY_COLOR1 = "#191925"
// TextColor
let PRIMARY_TEXT_COLOR_DARK = "#ffffff"
let SECONDARY_TEXT_COLOR_DARK = "#ffffff"
let BTN_TEXT_COLOR_DARK = "#ffffff"

// Banking App

let BANKING_PRIMARY = "#F4413D";
let BANKING_COLORPRIMARTDARK = "#FFF";

let BANKING_TEXTCOLORPRIMARY = "#070706";
let BANKING_TEXTCOLORSECONDARY = "#747474";
let BANKING_TEXTCOLORWHITE = "#FFFFFF";
let BANKING_TEXTCOLORORANGE = "#F4413D";
let BANKING_TEXTCOLORYELLOW = "#FFC107";

let BANKING_APP_BACKGROUND = "#f3f5f9";
let BANKING_BLACKCOLOR = "#070706";
let BANKING_VIEW_COLOR = "#DADADA";
let BANKING_BLACKLIGHTCOLOR = "#242525";
let BANKING_SHADOWCOLOR = "#95E9EBF0";
let BANKING_GREYCOLOR = "#A3A0A0";
let BANKING_BOTTOMEDITTEXTLINECOLOR = "#DBD9D9";
let BANKING_BACKGROUNDFRAGMENTCOLOR = "#F7F5F5";
let BANKING_YELLOWCOLOR = "#FFC107";
let BANKING_BALANCECOLOR = "#8ed16f";
let BANKING_WHITECOLOR = "#FFFFFF";
let BANKING_DARKBLUECOLOR = "#041887";
let BANKING_LIGHTBLUECOLOR = "#41479B";
let BANKING_LIGHTREDCOLOR = "#41479B";
let BANKING_DARKREDCOLOR = "#D80027";
let BANKING_LIGHTGREENCOLOR = "#05E10E";
let BANKING_SKYBLUECOLOR = "#03A9F4";
let BANKING_LIGHTORANGECOLOR = "#E7586A";
let BANKING_PURPLECOLOR = "#AD3AC3";


let FITNESS_PRIMARYLIGHT = "#EDA5BE";
let FITNESS_ACCENTCOLOR = "#03DAC5";
let FITNESS_STARTBACKGROUND = "#F4B6A1";

let FITNESS_TEXTCOLORPRIMARY = "#070706";
let FITNESS_TEXTCOLORSECONDARY = "#747474";
let FITNESS_GREYCOLOR = "#E5E5E5";
let FITNESS_WHITECOLOR = "#FFFFFF";
let FITNESS_CREATEPWD_BG = "#A28B85";
let FITNESS_BOTTOM_EDIT_TEXTLINE = "#DBD9D9";
let FITNESS_APP_BACKGROUND = "#F9F9F9";
